# Generated by Django 3.2.8 on 2021-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20211017_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='anonym_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
