# Generated by Django 3.2.8 on 2021-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20211017_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_card_max_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' Максимальный объем карты памяти'),
        ),
    ]
