# Generated by Django 3.2.8 on 2021-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_alter_smartphone_sd_card_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_card_max_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем SD'),
        ),
    ]
