# Generated by Django 3.2.8 on 2021-10-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_auto_20211021_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.customer', verbose_name='Пользователь'),
        ),
    ]
