# Generated by Django 3.2.8 on 2021-10-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20211021_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='final_amount',
            new_name='total_price',
        ),
    ]
