# Generated by Django 3.2.8 on 2021-11-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0013_auto_20211106_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='basket_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_basket', to='webshop.basket', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='basket_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_basket', to='webshop.basket', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='total_price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='total_price_uk',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='user_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_ru',
            field=models.ImageField(default='media/not.jpg', null=True, upload_to='', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_uk',
            field=models.ImageField(default='media/not.jpg', null=True, upload_to='', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название катеории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название катеории'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='brand_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Бренд ноутбука'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='brand_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Бренд ноутбука'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cpu_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cpu_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='diagonal_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Диагональ'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='diagonal_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Диагональ'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='display_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип дисплея'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='display_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип дисплея'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_product_ru',
            field=models.ImageField(null=True, upload_to='media/<django.db.models.fields.CharField>', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_product_uk',
            field=models.ImageField(null=True, upload_to='media/<django.db.models.fields.CharField>', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='name_product_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='name_product_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='order',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='adress_uk',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='basket_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.basket', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='order',
            name='basket_uk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.basket', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='order',
            name='buy_type_ru',
            field=models.CharField(choices=[('self-pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='self-pickup', max_length=100, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='buy_type_uk',
            field=models.CharField(choices=[('self-pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='self-pickup', max_length=100, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_ru',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_uk',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='webshop.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='webshop.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date_ru',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата получения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date_uk',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата получения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_uk',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_process', 'Обрабатывается менеджером'), ('on_the_way', 'В пути'), ('completed', 'Выполнен')], default='new', max_length=100, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uk',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_process', 'Обрабатывается менеджером'), ('on_the_way', 'В пути'), ('completed', 'Выполнен')], default='new', max_length=100, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='accum_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Объем аккумулятора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='accum_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Объем аккумулятора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Бренд смартфона'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Бренд смартфона'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='diagonal_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Диагональ'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='diagonal_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Диагональ'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип дисплея'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип дисплея'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_cam_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_cam_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_product_ru',
            field=models.ImageField(null=True, upload_to='media/<django.db.models.fields.CharField>', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_product_uk',
            field=models.ImageField(null=True, upload_to='media/<django.db.models.fields.CharField>', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='main_cam_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Главная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='main_cam_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Главная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='model_smart_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Модель смартфона'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='model_smart_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Модель смартфона'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='name_product_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='name_product_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ram_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ram_uk',
            field=models.CharField(max_length=64, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='resolution_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='resolution_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_card_max_size_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем SD'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_card_max_size_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем SD'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_card_ru',
            field=models.BooleanField(default=True, verbose_name='Возможность использования SD карты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_card_uk',
            field=models.BooleanField(default=True, verbose_name='Возможность использования SD карты'),
        ),
    ]
